export const colorMap = {
  green: {
    base: 'green',
    from: 'from-green-300',
    to: 'to-green-400',
    from2: 'from-green-500',
    to2: 'to-green-600',
  },
  blue: {
    base: 'blue',
    from: 'from-blue-300',
    to: 'to-blue-400',
    from2: 'from-blue-500',
    to2: 'to-blue-600',
  },
  red: {
    base: 'red',
    from: 'from-red-300',
    to: 'to-red-400',
    from2: 'from-red-500',
    to2: 'to-red-600',
  },
  yellow: {
    base: 'yellow',
    from: 'from-yellow-300',
    to: 'to-yellow-400',
    from2: 'from-yellow-500',
    to2: 'to-yellow-600',
  },
  gray: {
    base: 'gray',
    from: 'from-gray-300',
    to: 'to-gray-400',
    from2: 'from-gray-500',
    to2: 'to-gray-600',
  },
  purple: {
    base: 'purple',
    from: 'from-purple-300',
    to: 'to-purple-400',
    from2: 'from-purple-500',
    to2: 'to-purple-600',
  },
  pink: {
    base: 'pink',
    from: 'from-pink-300',
    to: 'to-pink-400',
    from2: 'from-pink-500',
    to2: 'to-pink-600',
  },
  indigo: {
    base: 'indigo',
    from: 'from-indigo-300',
    to: 'to-indigo-400',
    from2: 'from-indigo-500',
    to2: 'to-indigo-600',
  },
  teal: {
    base: 'teal',
    from: 'from-teal-300',
    to: 'to-teal-400',
    from2: 'from-teal-500',
    to2: 'to-teal-600',
  },
  amber: {
    base: 'amber',
    from: 'from-amber-300',
    to: 'to-amber-400',
    from2: 'from-amber-500',
    to2: 'to-amber-600',
  },
  emerald: {
    base: 'emerald',
    from: 'from-emerald-300',
    to: 'to-emerald-400',
    from2: 'from-emerald-500',
    to2: 'to-emerald-600',
  },
};
