# .github/workflows/deploy.yml
name: Deploy Vite Site to Locaweb via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Gerar build do Vite
        run: npm run build    
      - name: Deploy
        uses: actions/checkout@v2
      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
            host: ${{ secrets.HOST }} 
            user: ${{ secrets.USER }}
            password: ${{ secrets.PASS }}
            localDir: "dist"
